### ISSUE TITLE
istable issue

### ISSUE THREAD

**Issue by oktriplex** [Be1zebub/Discordia-True-Message-reply#1]
![изображение](https://user-images.githubusercontent.com/80281764/161647261-2cfa85b4-e97c-44bb-8b27-d427b20bc5b3.png)
![изображение](https://user-images.githubusercontent.com/80281764/161647437-79033829-68ea-4053-b7bb-3eb4df7ecc6b.png)

**Comment by Be1zebub** [comment]
solved, try now

**Comment by oktriplex** [comment]
now works =)
